exclude: |
    (?x)(
        ^tests/|
        ^log/
    )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: stable
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: ["--line-length", "120"]
        language_version: python3.10
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: stable
      - id: flake8
        args: ["--max-line-length", "120"]
        stages: [commit]
  - repo: https://github.com/asottile/seed-isort-config
    rev: stable
    hooks:
      - id: seed-isort-config
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: stable
    hooks:
      - id: isort
        args: ["--profile", "black"]
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: stable
    hooks:
      - id: prettier
        types_or: [json]
        stages: [commit]

